# Generated by Django 3.1.4 on 2020-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('cost_pax', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
